[project]
name = "ca-api-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "google-cloud>=0.34.0",
    "google-cloud-geminidataanalytics>=0.3.0",
    "pandas>=2.3.2",
]
